//! Adapter-style parsing library for `katha`.
//!
//! This crate provides format-specific parser adapters for `epub`, `docx`, and
//! `pdf` inputs and normalizes them into a shared [`Document`] schema.
//!
//! The normalization boundary lives in this crate:
//! - [`fetch_parser`] resolves an adapter from a file-type key.
//! - [`Parser`] defines the common parsing contract used by the CLI.
//! - [`Document`], [`Section`], and [`ContentBlock`] describe the canonical
//!   output model returned by every adapter.
//!
//! # Examples
//!
//! ```
//! use katha_parsers::{ContentBlock, ContentKind, Document, Section};
//! use std::collections::HashMap;
//!
//! let mut content = HashMap::new();
//! content.insert(
//!     0,
//!     vec![
//!         ContentBlock {
//!             kind: ContentKind::Heading,
//!             content: Some("Chapter 1".to_string()),
//!             items: Vec::new(),
//!             level: Some(1),
//!         },
//!         ContentBlock {
//!             kind: ContentKind::Paragraph,
//!             content: Some("Opening paragraph".to_string()),
//!             items: Vec::new(),
//!             level: None,
//!         },
//!     ],
//! );
//!
//! let document = Document {
//!     cover_image: String::new(),
//!     title: "Example Book".to_string(),
//!     subtitle: String::new(),
//!     author: "A. Writer".to_string(),
//!     language: "en".to_string(),
//!     description: "Normalized parser output".to_string(),
//!     toc: vec![Section {
//!         id: "chapter-1".to_string(),
//!         title: "Chapter 1".to_string(),
//!         content_ref: 0,
//!         children: Vec::new(),
//!     }],
//!     content,
//! };
//!
//! assert_eq!(document.toc[0].content_ref, 0);
//! assert_eq!(document.content[&0][0].kind, ContentKind::Heading);
//! ```

/// DOCX parser adapter.
pub mod docx;
/// EPUB parser adapter.
pub mod epub;
/// Parser error model and exit-code mapping.
pub mod error;
/// PDF parser adapter.
pub mod pdf;

use std::collections::HashMap;

use error::ParserError;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize)]
/// Canonical parsed document output shared by all parser adapters.
///
/// `toc` and `content` are linked through [`Section::content_ref`]. Each entry
/// in `content` contains semantic blocks instead of a single markdown string,
/// which allows downstream consumers to preserve headings, paragraphs, lists,
/// and quotes.
pub struct Document {
    /// Base64-encoded cover image data when available, otherwise empty.
    pub cover_image: String,
    /// Main document title.
    pub title: String,
    /// Optional subtitle.
    pub subtitle: String,
    /// Primary author/creator.
    pub author: String,
    /// Language code or language label reported by the source document.
    pub language: String,
    /// Human-readable description extracted from document metadata.
    pub description: String,
    /// Hierarchical table of contents.
    pub toc: Vec<Section>,
    /// Parsed chapter/section content keyed by [`Section::content_ref`].
    pub content: HashMap<usize, Vec<ContentBlock>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
/// Semantic content block extracted from a document section.
pub enum ContentKind {
    Heading,
    List,
    Paragraph,
    Quote,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// A normalized content block containing plain text.
///
/// Use `kind` to interpret which fields are populated:
/// - headings use `content` and `level`
/// - paragraphs and quotes use `content`
/// - lists use `items`
pub struct ContentBlock {
    /// Block semantic kind.
    pub kind: ContentKind,
    /// Plain text content for heading/paragraph/quote blocks.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Plain text list items for list blocks.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub items: Vec<String>,
    /// Heading depth when [`ContentKind::Heading`].
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<u8>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
/// A logical section in the parsed table of contents.
///
/// `content_ref` points to the body blocks stored in [`Document::content`].
pub struct Section {
    /// Stable unique section identifier generated by the parser.
    pub id: String,
    /// Section heading/title.
    pub title: String,
    /// Key used to resolve section body text from [`Document::content`].
    pub content_ref: usize,
    /// Child sections for nested document structures.
    pub children: Vec<Section>,
}

/// Common adapter contract implemented by all parser backends.
///
/// Parsers are stateful because some adapters cache parsed metadata or
/// intermediate content after the first read.
pub trait Parser {
    /// Parses the input source path and returns a normalized [`Document`].
    fn parse(&mut self, src: &str) -> Result<Document, ParserError>;
    /// Returns a base64-encoded cover payload when supported.
    fn get_cover(&mut self) -> Result<String, ParserError>;
    /// Returns the document title.
    fn get_title(&mut self) -> Result<String, ParserError>;
    /// Returns the document subtitle.
    fn get_subtitle(&mut self) -> Result<String, ParserError>;
    /// Returns the document author.
    fn get_author(&mut self) -> Result<String, ParserError>;
    /// Returns the document description.
    fn get_description(&mut self) -> Result<String, ParserError>;
    /// Returns the document publisher.
    fn get_publisher(&mut self) -> Result<String, ParserError>;
    /// Returns the document language.
    fn get_language(&mut self) -> Result<String, ParserError>;
    /// Returns the canonical cover image field for [`Document`].
    fn get_cover_image(&mut self) -> Result<String, ParserError>;
    /// Builds a hierarchical table of contents.
    fn get_toc(&mut self) -> Result<Vec<Section>, ParserError>;
    /// Returns parsed content chunks keyed by `content_ref`.
    fn get_content_by_chapter(&mut self) -> Result<HashMap<usize, Vec<ContentBlock>>, ParserError>;
    /// Converts parser-specific HTML/content fragments into plain text.
    fn clean_html(html: &str) -> Result<String, ParserError>
    where
        Self: Sized;
}

/// Supported parser keys accepted by [`fetch_parser`].
///
/// # Examples
///
/// ```
/// use katha_parsers::SUPPORTED_PARSERS;
///
/// assert_eq!(SUPPORTED_PARSERS, ["epub", "docx", "pdf"]);
/// ```
pub const SUPPORTED_PARSERS: [&str; 3] = ["epub", "docx", "pdf"];

/// Returns a parser adapter for a supported file type.
///
/// Supported keys are lowercase and currently match file extensions directly.
///
/// # Examples
///
/// ```
/// use katha_parsers::{fetch_parser, error::ParserError};
///
/// assert!(fetch_parser("epub").is_ok());
/// assert!(fetch_parser("docx").is_ok());
/// assert!(fetch_parser("pdf").is_ok());
/// assert!(matches!(
///     fetch_parser("unsupported"),
///     Err(ParserError::UndefinedParser)
/// ));
/// ```
pub fn fetch_parser(parser_type: &str) -> Result<Box<dyn Parser>, ParserError> {
    match parser_type {
        "epub" => Ok(Box::new(epub::Epub::new())),
        "docx" => Ok(Box::new(docx::Docx::new())),
        "pdf" => Ok(Box::new(pdf::Pdf::new())),
        _ => Err(ParserError::UndefinedParser),
    }
}
